services:
  client:
    build:
      context: ../routing-client
    volumes:
      - ../routing-client:/app
    ports:
      - 3000:3000
  routing:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 3001:3000
    environment:
      - DB_NAME=osm
      - DB_USER=osm
      - DB_PASSWORD=osm
      - DB_DATABASE=osm
      - DB_HOST=db
      - RUST_BACKTRACE=1
  osm2pgsql:
    build: 
      context: ./osm2pgsql
    volumes:
      - ./osm2pgsql:/app
  db:
    image: postgis/postgis
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: osm
      POSTGRES_USER: osm
      POSTGRES_DB: osm

volumes:
  pg-data: